/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package housemanagerpro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author param
 */
public class DeleteStudent extends javax.swing.JFrame {

    /**
     * Creates new form DeleteStudent
     */
    static String USERNAME= "root";
    static String PASSWORD= "";
    static String CONN_STRING ="jdbc:mysql://localhost:3306/ourdb?zeroDateTimeBehavior=convertToNull";
    static Connection conn= null;
    static PreparedStatement pst =null;
    static ResultSet rs=null;
    Student s= new Student();
    int rowindex=-1;
    boolean flag=false;
    
    public static void MySQL()
    {
        try
        {
            conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            System.out.println("connection successful!");
        } 
        catch (SQLException e)
        {
            System.out.println("error!");
        }
    }
    
    
    public DeleteStudent() {
        initComponents();
        MySQL();
        Display();
    }
    
    public ArrayList<Student> getStudentsList()
    {
       ArrayList<Student> studentsList = new ArrayList<Student>();
       try 
       {
           pst=conn.prepareStatement("SELECT * FROM students");
           rs=pst.executeQuery();
           Student student;
           while(rs.next())
           {
                student = new Student(rs.getString("Name"),rs.getString("Gender"),rs.getString("Grade"),rs.getString("Section"),rs.getString("DOB"),rs.getString("EmailID"),rs.getString("Phone"));
                studentsList.add(student);
           }

       } 
       catch (Exception e) 
       {
           System.out.println("error accessing database");
       }
       return studentsList;
    }
    
    public void Display()
    {
        ArrayList<Student> students= getStudentsList();
        students=sortStudents(students);
        DefaultTableModel model= (DefaultTableModel)Table_Database.getModel();
        int noOfRows=Table_Database.getRowCount();
        if(noOfRows!=0)
        {
            for(int i=(noOfRows-1); i>=0; i--)
                model.removeRow(i);
        }
        Object [] row= new Object[7];
        for(int i=0; i<students.size();i++)
        {
            row[0]=students.get(i).Name;
            row[1]=students.get(i).Gender;
            row[2]=students.get(i).Grade;
            row[3]=students.get(i).Section;
            row[4]=students.get(i).DOB;
            row[5]=students.get(i).Email;
            row[6]=students.get(i).Phone;   
            
            model.addRow(row);
        }
        
    }

       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_ListName = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Database = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        TextField_CurrentStudent = new javax.swing.JTextField();
        Button_Delete = new javax.swing.JButton();
        Button_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Label_ListName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_ListName.setText("DELETE A STUDENT");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Select a student from the Database and click \"Delete\"");

        Table_Database.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_Database.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Grade", "Section", "DOB", "EmailID", "Phone"
            }
        ));
        Table_Database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_DatabaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Database);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Student Selected:");

        TextField_CurrentStudent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TextField_CurrentStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_CurrentStudentActionPerformed(evt);
            }
        });

        Button_Delete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_Delete.setText("DELETE");
        Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteActionPerformed(evt);
            }
        });

        Button_Back.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_Back.setText("<BACK");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_CurrentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(422, 422, 422)
                            .addComponent(jLabel11))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Button_Back)
                                    .addGap(362, 362, 362)
                                    .addComponent(Label_ListName))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Back)
                    .addComponent(Label_ListName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextField_CurrentStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_Delete))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_CurrentStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_CurrentStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_CurrentStudentActionPerformed

    private void Table_DatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_DatabaseMouseClicked
        DefaultTableModel model=(DefaultTableModel) Table_Database.getModel();
        rowindex=Table_Database.getSelectedRow();
        s.Name=model.getValueAt(rowindex, 0).toString();
        s.Gender=model.getValueAt(rowindex, 1).toString();
        s.Grade=model.getValueAt(rowindex, 2).toString();
        s.Section=model.getValueAt(rowindex, 3).toString();
        s.DOB=model.getValueAt(rowindex, 4).toString();
        s.Email=model.getValueAt(rowindex,5).toString();
        s.Phone=model.getValueAt(rowindex,6).toString();
        TextField_CurrentStudent.setText(s.Name);
        flag=true;
    }//GEN-LAST:event_Table_DatabaseMouseClicked

    private void Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteActionPerformed
        if(flag)
        {
            try 
            {
                pst=conn.prepareStatement("DELETE FROM students WHERE EmailID=?");
                pst.setString(1, s.Email);
                pst.executeUpdate();
                Display();
                System.out.println("deleted successfully");
                TextField_CurrentStudent.setText("");
                JOptionPane.showMessageDialog(null,"The student has been deleted from the database.\nThe student details will no longer appear in the database.", "Student deleted successfully!", JOptionPane.INFORMATION_MESSAGE);  
                flag=false;
            } 
            catch (Exception e) 
            {
                System.out.println("error while adding student");
                JOptionPane.showMessageDialog(this,e);
            }

        }
        else
        {
             JOptionPane.showMessageDialog(null, "No student selected.\nPlease select a student from the Database and try again.", "No student selected", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Button_DeleteActionPerformed

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        int okOrCancel=JOptionPane.showConfirmDialog(null, "Are you sure you want to return to the home page?\nAny unsaved changes will be lost.", "Confirm Return", JOptionPane.OK_CANCEL_OPTION);
        if(okOrCancel==0)
        {
            EditDatabasePage edp= new EditDatabasePage();
            edp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Button_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteStudent().setVisible(true);
            }
        });
    }
     public ArrayList<Student> sortStudents(ArrayList<Student> students)
    {
        if(students.isEmpty() || students.size()==1)
        {
            return students;
        }
        else
        {
            for(int i=0;i<students.size();i++)
            {
                for(int j=0; j<(students.size()-i-1);j++)
                {
                    if(Integer.parseInt(students.get(j).Grade)<Integer.parseInt(students.get(j+1).Grade))
                    {
                        String tempName=students.get(j).Name;
                        String tempGender=students.get(j).Gender;
                        String tempGrade=students.get(j).Grade;
                        String tempSection=students.get(j).Section;
                        String tempDOB=students.get(j).DOB;
                        String tempEmail=students.get(j).Email;
                        String tempPhone=students.get(j).Phone;
                        students.get(j).Name=students.get(j+1).Name;
                        students.get(j).Gender=students.get(j+1).Gender;
                        students.get(j).Grade=students.get(j+1).Grade;
                        students.get(j).Section=students.get(j+1).Section;
                        students.get(j).DOB=students.get(j+1).DOB; 
                        students.get(j).Email=students.get(j+1).Email;
                        students.get(j).Phone=students.get(j+1).Phone; 
                        students.get(j+1).Name=tempName;
                        students.get(j+1).Gender=tempGender;
                        students.get(j+1).Grade=tempGrade;
                        students.get(j+1).Section=tempSection;
                        students.get(j+1).DOB=tempDOB; 
                        students.get(j+1).Email=tempEmail; 
                        students.get(j+1).Phone=tempPhone; 
                    }
                }
            }
        }
        return students;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_Delete;
    private javax.swing.JLabel Label_ListName;
    private javax.swing.JTable Table_Database;
    private javax.swing.JTextField TextField_CurrentStudent;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
