/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package housemanagerpro;

import javax.swing.JOptionPane;

/**
 *
 * @author param
 */
public class EditDatabasePage extends javax.swing.JFrame {

    /**
     * Creates new form EditDatabasePage
     */
    public EditDatabasePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Back = new javax.swing.JButton();
        Button_Save = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Label_ChangePassword = new javax.swing.JLabel();
        Button_BackToOvp = new javax.swing.JButton();
        Button_AddStudent = new javax.swing.JButton();
        Button_EditStudent = new javax.swing.JButton();
        Button_DeleteStudent = new javax.swing.JButton();
        Label_ChangePassword1 = new javax.swing.JLabel();

        Button_Back.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_Back.setText("<BACK");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        Button_Save.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_Save.setText("SAVE CHANGES");
        Button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SaveActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Label_ChangePassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_ChangePassword.setText("EDIT DATABASE");

        Button_BackToOvp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_BackToOvp.setText("<BACK");
        Button_BackToOvp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackToOvpActionPerformed(evt);
            }
        });

        Button_AddStudent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_AddStudent.setText("ADD A NEW STUDENT");
        Button_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AddStudentActionPerformed(evt);
            }
        });

        Button_EditStudent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_EditStudent.setText("EDIT A STUDENT");
        Button_EditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditStudentActionPerformed(evt);
            }
        });

        Button_DeleteStudent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_DeleteStudent.setText("DELETE A STUDENT");
        Button_DeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteStudentActionPerformed(evt);
            }
        });

        Label_ChangePassword1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Label_ChangePassword1.setText("What would you like to do?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Button_BackToOvp)
                        .addGap(147, 147, 147)
                        .addComponent(Label_ChangePassword))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_AddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_EditStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_DeleteStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ChangePassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ChangePassword)
                    .addComponent(Button_BackToOvp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_ChangePassword1)
                .addGap(62, 62, 62)
                .addComponent(Button_AddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_EditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        int okOrCancel=JOptionPane.showConfirmDialog(null, "Are you sure you want to return to the Home Page? \nAny unsaved changes will be lost.", "Confirm Return", JOptionPane.OK_CANCEL_OPTION);
        if(okOrCancel==0)
        {
            this.dispose();
            OverviewPage overview= new OverviewPage();
            overview.setVisible(true);
        }
    }//GEN-LAST:event_Button_BackActionPerformed

    private void Button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SaveActionPerformed

    }//GEN-LAST:event_Button_SaveActionPerformed

    private void Button_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AddStudentActionPerformed
        AddStudent as= new AddStudent();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_AddStudentActionPerformed

    private void Button_EditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditStudentActionPerformed
        EditStudent es=new EditStudent();
        es.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_EditStudentActionPerformed

    private void Button_DeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteStudentActionPerformed
        DeleteStudent ds= new DeleteStudent();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_DeleteStudentActionPerformed

    private void Button_BackToOvpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackToOvpActionPerformed
        this.dispose();
        OverviewPage overview= new OverviewPage();
        overview.setVisible(true);
    }//GEN-LAST:event_Button_BackToOvpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDatabasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDatabasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDatabasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDatabasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDatabasePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_AddStudent;
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_BackToOvp;
    private javax.swing.JButton Button_DeleteStudent;
    private javax.swing.JButton Button_EditStudent;
    private javax.swing.JButton Button_Save;
    private javax.swing.JLabel Label_ChangePassword;
    private javax.swing.JLabel Label_ChangePassword1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
