/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package housemanagerpro;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author param
 */
public class ViewDatabasePage extends javax.swing.JFrame {

    /**
     * Creates new form ViewDatabasePage
     */
    ArrayList<Student> students= new ArrayList<Student>();
    public ViewDatabasePage() {
        initComponents();
        MySQL();
        Display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_ListName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Database = new javax.swing.JTable();
        Button_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Label_ListName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_ListName.setText("STUDENT DATABASE");

        Table_Database.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Table_Database.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Grade", "Section", "DOB", "Email ID", "Phone"
            }
        ));
        jScrollPane1.setViewportView(Table_Database);
        if (Table_Database.getColumnModel().getColumnCount() > 0) {
            Table_Database.getColumnModel().getColumn(0).setMinWidth(150);
            Table_Database.getColumnModel().getColumn(0).setPreferredWidth(150);
            Table_Database.getColumnModel().getColumn(0).setMaxWidth(150);
            Table_Database.getColumnModel().getColumn(1).setMinWidth(100);
            Table_Database.getColumnModel().getColumn(1).setPreferredWidth(100);
            Table_Database.getColumnModel().getColumn(1).setMaxWidth(100);
            Table_Database.getColumnModel().getColumn(2).setMinWidth(100);
            Table_Database.getColumnModel().getColumn(2).setPreferredWidth(100);
            Table_Database.getColumnModel().getColumn(2).setMaxWidth(100);
            Table_Database.getColumnModel().getColumn(3).setMinWidth(100);
            Table_Database.getColumnModel().getColumn(3).setPreferredWidth(100);
            Table_Database.getColumnModel().getColumn(3).setMaxWidth(100);
            Table_Database.getColumnModel().getColumn(4).setMinWidth(100);
            Table_Database.getColumnModel().getColumn(4).setPreferredWidth(100);
            Table_Database.getColumnModel().getColumn(4).setMaxWidth(100);
            Table_Database.getColumnModel().getColumn(6).setMinWidth(150);
            Table_Database.getColumnModel().getColumn(6).setPreferredWidth(150);
            Table_Database.getColumnModel().getColumn(6).setMaxWidth(150);
        }

        Button_Back.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Button_Back.setText("<BACK");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_ListName)
                        .addGap(523, 523, 523))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ListName)
                    .addComponent(Button_Back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static String USERNAME= "root";
    static String PASSWORD= "";
    static String CONN_STRING ="jdbc:mysql://localhost:3306/ourdb?zeroDateTimeBehavior=convertToNull";
    static Connection conn= null;
    static PreparedStatement pst =null;
    static ResultSet rs=null;
    public static void MySQL()
    {
        try
        {
            conn = DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
            System.out.println("connection successful!");
        } 
        catch (SQLException e)
        {
            System.out.println("error!");
        }
    }
    
    public void getStudentsList()
    {
       try 
       {
           pst=conn.prepareStatement("SELECT * FROM students");
           rs=pst.executeQuery();
           Student student;
           while(rs.next())
           {
                student = new Student(rs.getString("Name"),rs.getString("Gender"),rs.getString("Grade"),rs.getString("Section"),rs.getString("DOB"),rs.getString("EmailID"),rs.getString("Phone"));
                students.add(student);
           }

       } 
       catch (Exception e) 
       {
           System.out.println("error accessing database");
       }
    }
    
    public void Display()
    {
        getStudentsList();
        sortStudents();
        DefaultTableModel model= (DefaultTableModel)Table_Database.getModel();
        Object [] row= new Object[7];
        for(int i=0; i<students.size();i++)
        {
            row[0]=students.get(i).Name;
            row[1]=students.get(i).Gender;
            row[2]=students.get(i).Grade;
            row[3]=students.get(i).Section;
            row[4]=students.get(i).DOB;
            row[5]=students.get(i).Email;
            row[6]=students.get(i).Phone;   
            
            model.addRow(row);
        }
        
    }
    
    public void sortStudents()
    {
        if(students.isEmpty() || students.size()==1)
        {
            return;
        }
        else
        {
            for(int i=0;i<students.size();i++)
            {
                for(int j=0; j<(students.size()-i-1);j++)
                {
                    if(Integer.parseInt(students.get(j).Grade)<Integer.parseInt(students.get(j+1).Grade))
                    {
                        String tempName=students.get(j).Name;
                        String tempGender=students.get(j).Gender;
                        String tempGrade=students.get(j).Grade;
                        String tempSection=students.get(j).Section;
                        String tempDOB=students.get(j).DOB;
                        String tempEmail=students.get(j).Email;
                        String tempPhone=students.get(j).Phone;
                        students.get(j).Name=students.get(j+1).Name;
                        students.get(j).Gender=students.get(j+1).Gender;
                        students.get(j).Grade=students.get(j+1).Grade;
                        students.get(j).Section=students.get(j+1).Section;
                        students.get(j).DOB=students.get(j+1).DOB; 
                        students.get(j).Email=students.get(j+1).Email;
                        students.get(j).Phone=students.get(j+1).Phone; 
                        students.get(j+1).Name=tempName;
                        students.get(j+1).Gender=tempGender;
                        students.get(j+1).Grade=tempGrade;
                        students.get(j+1).Section=tempSection;
                        students.get(j+1).DOB=tempDOB; 
                        students.get(j+1).Email=tempEmail; 
                        students.get(j+1).Phone=tempPhone; 
                    }
                }
            }
        }
    }

    
    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        this.dispose();
        OverviewPage overview= new OverviewPage();
        overview.setVisible(true);
    }//GEN-LAST:event_Button_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDatabasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDatabasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDatabasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDatabasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDatabasePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JLabel Label_ListName;
    private javax.swing.JTable Table_Database;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
